### ISSUE TITLE
Sorting by "Join to Court score" is not correct with latest CK3 versions

### ISSUE THREAD

**Issue by stoyanr** [Vasolik/CK3ACS#6]
Sorting by "Join to Court score" is not correct with latest CK3 versions (1.7.*, 1.8.*). The interaction `invite_to_court_interaction` in the base game has been updated to include additional modifiers to `ai_accept`, such as additional willingness to join court for wandering characters, impact of court amenities, etc. However, this is not reflected in the `acs_invite_to_court` value that calculates the score for the above sorting.

**Comment by Vasolik** [comment]
I do not have time at the moment to work on the mod. But I would not mind if you make a PR with a fix :)

**Comment by stoyanr** [comment]
@Vasolik done, see #7. This was my intention from the beginning.

**Comment by Vasolik** [comment]
@stoyanr I would not mind if you make even more contributions. For example, I think there are some new traits that are missing. Also, the implementation of culture search is similar to religion search. Also search for artefact per level and type of artefact is missing.

I am swamped myself, so I will hardly be able to do it any time soon or ever.
